#!/bin/sh

if git branch | grep -q -E ' master$'
then
	if [ "z`git diff origin HEAD editor.user.js spelling-corrections.txt content-free-words.txt example-domain-words.txt file-extensions.txt top-level-domains.txt`" != "z" ]
	then
		# editor.user.js or included files have been updated
		if [ "z`git diff origin HEAD version`" == "z" ]
		then
			# version has not been updated
			if [ "z`git diff HEAD version`" == "z" ]
			then
				echo "Version must be bumped before push. Run"
				echo "./bump-version.sh"
				echo "with an argument of patch, minor, or major"
				echo "and commit the changes"
				exit 1
			else
				echo "Version bump must be committed before push."
				exit 1
			fi
		fi
	fi
fi
